### ISSUE TITLE
Starbuncles Dupe Fluids with PNC's Thermopneumatic Processing Plant

### ISSUE THREAD

**Issue by MuteTiefling** [Alexthw46/StarbuncleMania#11]
Just linking this here as I'm uncertain where the actual bug lies. If it's in PNC or Starbuncle Mania. 

https://github.com/TeamPneumatic/pnc-repressurized/issues/1277

Details are in the link

**Comment by desht** [comment]
At https://github.com/Alexthw46/StarbuncleMania/blob/1.19.2/src/main/java/alexthw/starbunclemania/starbuncle/fluid/FluidExtractGoal.java#L79C89-L79C89 - the code here should use the result of `fluidHandlerExtract.drain()` _and nothing else_ to determine what has actually been extracted.

Instead the code is finding the first non-empty tank in the fluid handler and creating a new fluidstack from the contents of that (in the case of the TPP, that's the input tank), then calling `drain()` without checking the result (attempting to drain the input tank of the TPP in this way always gets an empty fluidstack).

And thus, a fluid dupe.
