### ISSUE TITLE
Conversion of Source to liquid form and back is significantly lossy (~10%)

### ISSUE THREAD

**Issue by dtangres** [Alexthw46/StarbuncleMania#13]
Converting a given volume of raw Source to its fluid form, then back again, results in a significant net loss of Source.

To replicate: 
1. Supply 8000 mB worth of Lava to a Fluid Sourcelink. You'll obtain 1 Source Jar and 28% worth of raw Source.
2. Transfer the source to a Fluid Containment Jar using a Source Condenser and an intermediate Source Jar. You'll obtain 12,000 mB of Liquid Source. with 8% left over (which would have been 800 mB if the Source Condenser wasn't restricted to increments of 10% in its input).
3. Use a Fluid Sourcelink on the Fluid Containment Jar to transfer raw Source into nearby Source Jars, including the jar holding the remainder 8% from the last step. You'll obtain 1 Jar + 15% worth of Source.
Assuming 1% of a Source Jar is equivalent to 100 mB of Liquid Source, this results in a loss of 1300 mB of Source - over a bucket's worth, and a total 10.15625% loss overall. 

Pack: Custom pack; however, no other mods besides Ars Nouveau and Starbuncle Mania were used to rest this example.

Pictures are provided below. 

Starting reagents:
![2024-03-12_21 48 49](https://github.com/Alexthw46/StarbuncleMania/assets/14242403/7ac9e216-4884-480e-8c9d-e260beb9f826)

Step 1:
![2024-03-12_21 45 21](https://github.com/Alexthw46/StarbuncleMania/assets/14242403/e6c3674c-ee99-405f-8870-81ba4155703d)

Step 2:
![2024-03-12_21 46 08](https://github.com/Alexthw46/StarbuncleMania/assets/14242403/d9124cbc-7efc-4caf-bdd6-e629027c5da2)
![2024-03-12_21 46 19](https://github.com/Alexthw46/StarbuncleMania/assets/14242403/e0de6abf-fc9a-4056-9c69-b9dab1112ab7)

Step 3:
![2024-03-12_21 47 18](https://github.com/Alexthw46/StarbuncleMania/assets/14242403/90cd826e-822d-46e3-bca1-9f22a4c843f7)

**Comment by dtangres** [comment]
I might be a fool. I just looked into the mod data and the conversion rate for liquid source into raw source is, in fact, 90%. This is a non-issue and the mod is working as intended. I guess that's the price you pay for mass storage.

It'd be lovely if this transfer rate were configurable in this or future versions.

**Comment by Alexthw46** [comment]
Source to fluid is in configs, fluids to source is a recipe (so datapackable)
