### ISSUE TITLE
Unable to set custom fluids for the Fluid Source Link

### ISSUE THREAD

**Issue by MuteTiefling** [Alexthw46/StarbuncleMania#3]
version: starbunclemania-1.19.2-1.0.5
logs: [latest.log](https://github.com/Alexthw46/StarbuncleMania/files/10397676/latest.log)

When setting the following for custom fluids, upon loading the world they get reverted back to defaults.

`fluid_to_source = ["industrialforegoing:ether_gas=5.0", "starbunclemania:source_fluid=0.9", "pneumaticcraft:biodiesel=0.5", "immersiveengineering:biodiesel=0.5", "industrialforegoing:sludge=0.1"]`

It seems no matter what I put, they get reset, even just setting it to 
`fluid_to_source = ["starbunclemania:source_fluid=0.9", "minecraft:lava=1.6", "minecraft:milk=0.2"]`

**Comment by SlugsturGH** [comment]
I'm having this issue as well, but im on 1.21.1 1.4.0.1.
No matter what i put it, when i load the game the config empties itself again. Nothing stays between the brackets.
