### ISSUE TITLE
Pick up fluid not inputting fluid in hotbar as description says

### ISSUE THREAD

**Issue by genesy** [Alexthw46/StarbuncleMania#4]
It just disappears. I tried with bucket and pneumatic tanks

**Comment by Alexthw46** [comment]
Buckets are blacklisted because they don't work as intended, i'll have to check for pneumaticraft

**Comment by Alexthw46** [comment]
should be fixed by https://www.curseforge.com/minecraft/mc-mods/starbunclemania/files/4400524, now buckets should work too
