### ISSUE TITLE
Crash while wanding Starby with Trash equipped

### ISSUE THREAD

**Issue by MuteTiefling** [Alexthw46/StarbuncleMania#6]
Just relaying quickly. If you Sneak Right Click a starby with a trash, it crashes the game.

https://gnomebot.dev/paste/1121764798103830569

Version: starbunclemania-1.19.2-1.0.6.jar 

Also, equipping the trash makes the texture break: 

![image](https://github.com/Alexthw46/StarbuncleMania/assets/9543430/955f1c1e-a532-4136-b9ef-46c91fcc6c4c)

**Comment by Alexthw46** [comment]
Oh, missed this mail. Surely caused by latest ars update
