### ISSUE TITLE
[1.19.2, 1.0.6] Starbuncles doesn't pick up fluids from cauldrons

### ISSUE THREAD

**Issue by iarspider** [Alexthw46/StarbuncleMania#7]
Title says it all - you can't bind Starbuncle with bucket to a cauldron. Is it intentional or not?

**Comment by Alexthw46** [comment]
Ye, intentional. If you add a mod that turns cauldrons into actual liquid containers it will work. Otherwise you need a fluid pickup turret. It would mess up too much to hardcode the cauldron behaviors for starbs as well, while for the turret + glyph it's way simpler.

**Comment by iarspider** [comment]
But turrets cost source :stuck_out_tongue: Thanks!
