### ISSUE TITLE
Fluid Sourcelink is over consuming fluids

### ISSUE THREAD

**Issue by MuteTiefling** [Alexthw46/StarbuncleMania#8]
starbunclemania-1.19.2-1.0.9

Test setup looks like this: 
![image](https://github.com/Alexthw46/StarbuncleMania/assets/9543430/d3de1235-c36b-475e-ba37-05543946059b)

I then add liquefied source to the tank until the sourcelink is at 100%

![image](https://github.com/Alexthw46/StarbuncleMania/assets/9543430/4a0b1c2d-806e-4fe4-bd6c-b6bcdcac8a5e)

The recipe loaded in the Imbuement Chamber is a modified Abjuration Essence recipe. It requires 500 Source: 

![image](https://github.com/Alexthw46/StarbuncleMania/assets/9543430/aa62e718-3d37-460a-9841-14eeb7e80aa6)

Our recipe for Liquefied > Source is 0.9 
https://github.com/EnigmaticaModpacks/Enigmatica9/blob/a7f22b4ad40ac09de002bde516e2195e52080e39/kubejs/server_scripts/base/recipes/starbunclemania/fluid_sourcelink.js#L11

So I would expect crafting one essence to cost less than one bucket. Unfortunately, it appears to consume far more. 4 buckets, in fact. 

![image](https://github.com/Alexthw46/StarbuncleMania/assets/9543430/171d2816-f83b-4ab5-b430-d4db3bfcaf62)

Original report: https://github.com/EnigmaticaModpacks/Enigmatica9/issues/783

**Comment by Alexthw46** [comment]
spotted the issue, the sourcelink was checking the conversion ratio as the amount to fill, instead of mult it for the amount of fluid to consume

**Comment by Alexthw46** [comment]
sent the version with the fix to curse, also the fix for the trash behavior not resetting

**Comment by MuteTiefling** [comment]
Awesome! Thanks!
