### ISSUE TITLE
starbunclemania liquidsourcelink thingy rendering oddly

### ISSUE THREAD

**Issue by kragnoth** [Alexthw46/StarbuncleMania#9]
when consuming lava or liquid source, the whole thing renders with the minecraft spritesheet instead of the proper texture, and the lava or source fluid gets rendered off to the side.  Don't have any rendering mod addons to the best of my knowledge.  Version is 1.2.0.4 for 1.20.1

**Comment by Alexthw46** [comment]
for some reason i was certain i fixed this, but apparently it was only the source condenser. It was caused by a change in the render library that was not addressed properly after porting. will release soon
